version: '2'
services:

 web:
  image: amitb26j/logging-stack-microservices_web
  ports:
   - "8080:8080"
  links:
   - logstash 
  networks:
   - logging-network

 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
  container_name: elasticsearch
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 2g
  cap_add:
    - IPC_LOCK
  volumes:
    - esdata1:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
    - logging-network

 logstash:
  image: logstash
  container_name: logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
   - ./src/main/logstash/conf:/etc/logstash/conf.d
  ports:
   - "5001:5001"
  networks:
   - logging-network

 kibana:
  image: kibana
  container_name: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
   - "5601:5601"
  networks:
   - logging-network

volumes:
  esdata1:
    driver: local

networks:
  logging-network:
   driver: bridge